// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionInput: typeof import('./components/ActionInput.vue')['default']
    ActionInputM: typeof import('./components/ActionInputM.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Charty: typeof import('./components/Charty.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notificationy: typeof import('./components/Notificationy.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
