# Generated by Django 4.0.3 on 2022-03-05 15:48

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_measurement_measurementstation_remove_metric_station_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementstation',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='roomnumber',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_co2',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='Station',
            new_name='fk_measurement_station',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_humidity',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_temperature',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='measurementstation',
            old_name='Classroom',
            new_name='fk_classroom',
        ),
        migrations.RenameField(
            model_name='measurementstation',
            old_name='station_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='measurement',
            name='light',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 millisecond'),
        ),
        migrations.CreateModel(
            name='EntranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('change', models.IntegerField()),
                ('measurement_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 millisecond')),
                ('fk_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
            ],
            options={
                'ordering': ['-measurement_time'],
            },
        ),
    ]
