# Generated by Django 3.1.14 on 2022-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220308_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='co2',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='humidity',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='light',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='motion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
