# Generated by Django 3.1.14 on 2022-03-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220316_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionHistory',
        ),
    ]
