# Generated by Django 3.1.14 on 2022-03-22 13:41

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_connectionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entranceevent',
            options={'ordering': ['-insert_time']},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-insert_time']},
        ),
        migrations.RenameField(
            model_name='entranceevent',
            old_name='measurement_time',
            new_name='insert_time',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_time',
            new_name='insert_time',
        ),
        migrations.CreateModel(
            name='ConnectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('insert_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 millisecond')),
                ('ip_address', models.GenericIPAddressField()),
                ('bluetooth_connected', models.BooleanField(default=False, null=True)),
                ('wlan_signal_strength', models.IntegerField()),
                ('ping_backend', models.IntegerField()),
                ('ping_broker', models.IntegerField()),
                ('ping_grafana', models.IntegerField()),
                ('fk_measurement_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.measurementstation')),
            ],
            options={
                'ordering': ['-insert_time'],
            },
        ),
    ]
